# name of your workflow
name: CI/CD Workflow for my Joke API

# trigger
on:
    workflow_dispatch 

jobs:
    code-checker:
        runs-on: ubuntu-latest

        steps:
            - name: checkout git repo
            - uses: actions/checkout@v6
              with:
                repository: ${{ github.repository }}

            - name: display pwd
              run: pwd

            - name: list content
              run: ls





